### ISSUE TITLE
parallel_rollout.py Bug

### ISSUE THREAD

**Issue by Shentl** [zbzhu99/NGSIM_SMARTS#11]
When i run  parallel_rollout.py, I get a "TypeError: <lambda>() got an unexpected keyword argument 'sim_name'' mistake

detailed mistake message:"
Process Worker-<ParallelEnv>-<1>:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tianle/Desktop/RL_project/NGSIM_SMARTS/SMARTS/smarts/env/wrappers/parallel_env.py", line 298, in _worker
    env = cloudpickle.loads(env_constructor)(sim_name=name)
TypeError: <lambda>() got an unexpected keyword argument 'sim_name'

...

Traceback (most recent call last):
  File "parallel_rollout.py", line 14, in <module>
    vector_env = ParallelEnv([env_creator] * env_num, auto_reset=True)

"

**Comment by zbzhu99** [comment]
Please try update SMARTS to required version (46c3497) and rebuild the scenario.
