### ISSUE TITLE
make: *** [sanity-test] Error 5

### ISSUE THREAD

**Issue by BravoFr0st** [zbzhu99/NGSIM_SMARTS#3]
[make: *** [sanity-test] Error 5]

**[Windows11 with WSL2(Ubuntu-18.04 LTS)**

**Problems**
make: *** [sanity-test] Error 5

但是logfile:
<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" hostname="LZY-GA401IU" name="pytest" skipped="0" tests="0" time="0.684" timestamp="2021-11-21T23:50:17.162407" /></testsuite$

不认为有错

随后的scl scenario build --clean scenarios/loop报错

Ubuntu-18.04是全新镜像

**Comment by zbzhu99** [comment]
看一下 `scl scenario build --clean scenarios/loop` 具体的报错信息？

**Comment by BravoFr0st** [comment]
```
Traceback (most recent call last):
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/bin/scl", line 33, in <module>
    sys.exit(load_entry_point('smarts', 'console_scripts', 'scl')())
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/cli/studio.py", line 54, in build_scenario
    _build_single_scenario(clean, allow_offset_map, scenario)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/cli/studio.py", line 77, in _build_single_scenario
    generate_glb_from_sumo_network(map_net, str(map_glb))
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/sstudio/sumo2mesh.py", line 27, in generate_glb_from_sumo_network
    glb = road_network.build_glb()
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 394, in build_glb
    return self._make_glb_from_polys(polys)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 390, in _make_glb_from_polys
    return GLBData(gltf.export_glb(scene, extras=metadata, include_normals=True))
TypeError: export_glb() got an unexpected keyword argument 'extras'
```

另外在`make sanity-test`的时候，会出现（大量Thread的报错是一样的）
```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/cli/studio.py", line 77, in _build_single_scenario
    generate_glb_from_sumo_network(map_net, str(map_glb))
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/sstudio/sumo2mesh.py", line 27, in generate_glb_from_sumo_network
    glb = road_network.build_glb()
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 394, in build_glb
    return self._make_glb_from_polys(polys)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 390, in _make_glb_from_polys
    return GLBData(gltf.export_glb(scene, extras=metadata, include_normals=True))
TypeError: export_glb() got an unexpected keyword argument 'extras'
```


这两个地方报错的共通项是
```
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/cli/studio.py", line 77, in _build_single_scenario
    generate_glb_from_sumo_network(map_net, str(map_glb))
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/sstudio/sumo2mesh.py", line 27, in generate_glb_from_sumo_network
    glb = road_network.build_glb()
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 394, in build_glb
    return self._make_glb_from_polys(polys)
  File "/home/lzy123/NGSIM_SMARTS/SMARTS/smarts/core/sumo_road_network.py", line 390, in _make_glb_from_polys
    return GLBData(gltf.export_glb(scene, extras=metadata, include_normals=True))
TypeError: export_glb() got an unexpected keyword argument 'extras'
```

**Comment by BravoFr0st** [comment]
`sumo=1.10.0`

**Comment by zbzhu99** [comment]
Try install an alternative version of `trimesh`:

```bash
pip install trimesh==3.9.20
```

**Comment by BravoFr0st** [comment]
```
(.venv) lzy123@LZY-GA401IU:~/NGSIM_SMARTS/SMARTS$ scl scenario build --clean scenarios/loop
build-scenario scenarios/loop
Installing scenario dependencies via '/home/lzy123/NGSIM_SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/loop/requirements.txt'
(.venv) lzy123@LZY-GA401IU:~/NGSIM_SMARTS/SMARTS$
```
似乎一切正常了

这之后是不是无运行`make sanity-test`的必要

**Comment by BravoFr0st** [comment]
更换版本后
```
(.venv) lzy123@LZY-GA401IU:~/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS$ make sanity-test
scl scenario build-all scenarios
build-scenario scenarios/loop
build-scenario scenarios/minicity
build-scenario scenarios/minicity
build-scenario scenarios/tests/same_location
build-scenario scenarios/tests/same_location
build-scenario scenarios/zoo_intersection
build-scenario scenarios/zoo_intersection
build-scenario scenarios/cloverleaf
build-scenario scenarios/intersections/2lane
build-scenario scenarios/intersections/2lane
build-scenario scenarios/intersections/2lane_circle
build-scenario scenarios/intersections/4lane
build-scenario scenarios/intersections/4lane
build-scenario scenarios/intersections/6lane
build-scenario scenarios/intersections/6lane
build-scenario scenarios/intersections/4lane_t
build-scenario scenarios/figure_eight
build-scenario scenarios/straight
build-scenario scenarios/behavior_models/uturn/4lane
build-scenario scenarios/behavior_models/uturn/4lane
build-scenario scenarios/behavior_models/uturn/1lane
build-scenario scenarios/behavior_models/uturn/1lane
build-scenario scenarios/behavior_models/cutin/1lane_agent_ahead
build-scenario scenarios/behavior_models/cutin/1lane_parallel_start
build-scenario scenarios/behavior_models/cutin/1lane_parallel_start
Waiting on scenarios/loop/map.net.xml ...
Installing scenario dependencies via '/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/intersections/4lane_t/requirements.txt'
Installing scenario dependencies via '/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/loop/requirements.txt'
Waiting on scenarios/minicity/shifted_map-AUTOGEN.net.xml ...
Installing scenario dependencies via '/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/minicity/requirements.txt'
Installing scenario dependencies via '/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/minicity/requirements.txt'
Waiting on scenarios/minicity/map.net.xml ...
Waiting on scenarios/cloverleaf/map.net.xml ...
Waiting on scenarios/tests/same_location/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/tests/same_location/map.net.xml ...
Waiting on scenarios/zoo_intersection/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/zoo_intersection/map.net.xml ...
Waiting on scenarios/intersections/2lane/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/intersections/2lane/map.net.xml ...
Waiting on scenarios/intersections/2lane_circle/map.net.xml ...
Waiting on scenarios/intersections/4lane/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/intersections/4lane/map.net.xml ...
Waiting on scenarios/intersections/6lane/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/intersections/6lane/map.net.xml ...
Waiting on scenarios/intersections/4lane_t/map.net.xml ...
Waiting on scenarios/figure_eight/map.net.xml ...
Waiting on scenarios/straight/map.net.xml ...
Waiting on scenarios/behavior_models/uturn/4lane/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/behavior_models/uturn/4lane/map.net.xml ...
Waiting on scenarios/behavior_models/uturn/1lane/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/behavior_models/uturn/1lane/map.net.xml ...
Waiting on scenarios/behavior_models/cutin/1lane_agent_ahead/map.net.xml ...
Waiting on scenarios/behavior_models/cutin/1lane_parallel_start/shifted_map-AUTOGEN.net.xml ...
Waiting on scenarios/behavior_models/cutin/1lane_parallel_start/map.net.xml ...
./tests/test_setup.py
PYTHONHASHSEED=42 pytest -v \
        --doctest-modules \
        --forked \
        --dist=loadscope \
        --junitxml="sanity_test_result.xml" \
        -n `nproc --ignore 2` \
        ./smarts/core/tests/test_python_version.py::test_python_version \
        ./smarts/core/tests/test_sumo_version.py::test_sumo_version \
        ./smarts/core/tests/test_dynamics_backend.py::test_set_pose \
        ./smarts/core/tests/test_sensors.py::test_waypoints_sensor \
        ./smarts/core/tests/test_smarts.py::test_smarts_doesnt_leak_tasks_after_reset \
        ./tests/test_examples.py::test_examples[multi_agent] \
        ./tests/test_examples.py::test_multi_instance_example \
        ./smarts/env/tests/test_social_agent.py::test_social_agents
/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/pytest_benchmark/logger.py:46: PytestBenchmarkWarning: Benchmarks are automatically disabled because xdist plugin is active.Benchmarks cannot be performed reliably in a parallelized environment.
  warner(PytestBenchmarkWarning(text))
==================================== test session starts =====================================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7
cachedir: .pytest_cache
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS
plugins: xdist-2.4.0, forked-1.3.0, notebook-0.6.1, cov-3.0.0, benchmark-3.4.1, anyio-3.3.4
[gw0] linux Python 3.7.12 cwd: /home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS
[gw1] linux Python 3.7.12 cwd: /home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS
[gw0] Python 3.7.12 (default, Sep 10 2021, 00:21:48)  -- [GCC 7.5.0]
[gw1] Python 3.7.12 (default, Sep 10 2021, 00:21:48)  -- [GCC 7.5.0]
gw0 [0] / gw1 [0]
scheduling tests via LoadScopeScheduling

- generated xml file: /home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/sanity_test_result.xml -
=================================== no tests ran in 0.68s ====================================
Makefile:21: recipe for target 'sanity-test' failed
make: *** [sanity-test] Error 5
```
不报错，仍然`Error 5`
```
(.venv) lzy123@LZY-GA401IU:~/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS$ scl scenario build --clean scenarios/loop
build-scenario scenarios/loop
Installing scenario dependencies via '/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/bin/python3.7 -m pip install -r scenarios/loop/requirements.txt'
(.venv) lzy123@LZY-GA401IU:~/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS$
```
无报错

但是```scl run --envision examples/single_agent.py scenarios/loop```报错
```
tcgetpgrp failed: Not a tty
/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/ale_py/roms/utils.py:90: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for external in metadata.entry_points().get(self.group, []):
Traceback (most recent call last):
  File "/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/gym/envs/registration.py", line 139, in spec
    importlib.import_module(mod_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'smarts.env'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/single_agent.py", line 80, in <module>
    seed=args.seed,
  File "examples/single_agent.py", line 51, in main
    seed=seed,
  File "/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/gym/envs/registration.py", line 128, in make
    spec = self.spec(path)
  File "/home/lzy123/SJTU-AI3601-Project-NGSIM-SMARTS/SMARTS/.venv/lib/python3.7/site-packages/gym/envs/registration.py", line 143, in spec
    mod_name
gym.error.Error: A module (smarts.env) was specified for the environment but was not found, make sure the package is installed with `pip install` before calling `gym.make()`
Killed
```
` 'smarts.env'`包从来没有在安装过程中出现过

**Comment by zbzhu99** [comment]
Sorry, the default `.gitignore` file for python provided by Github ignores `env/` folders. I have updated the gitignore file and uploaded smarts/env.

**Comment by BravoFr0st** [comment]
```scl run --envision examples/single_agent.py scenarios/loop```现在工作正常。
